// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efvmioanogdmappaeaoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmdm1pb2Fub2dkbWFwcGFlYW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NTcwMDUsImV4cCI6MjA1MzQzMzAwNX0.J9m11P9AMFtO4DbMpsQxVe4VrNreU4PjNdnTrnnLhs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);